SELECT * FROM DEMO_DB.PUBLIC.CALL_CENTER lIMIT 10;

UPDATE DEMO_DB.PUBLIC.CALL_CENTER
SET CC_COMPANY_NAME = 'prince'
WHERE CC_COMPANY_NAME = 'pri';

BEGIN NAME t1;

UPDATE DEMO_DB.PUBLIC.CALL_CENTER
SET CC_COMPANY_NAME = 'pri'
WHERE CC_COMPANY_NAME = 'prince';

SELECT COUNT(*)
FROM DEMO_DB.PUBLIC.CALL_CENTER
WHERE CC_COMPANY_NAME = 'pri';

SELECT SYSTEM$ABORT_TRANSACTION('<>');

SELECT CURRENT_TRANSACTION();
COMMIT;
ROLLBACK;
SHOW PARAMETERS ;





