USE database DEMO_DB;

CREATE OR REPLACE warehouse w1 with
warehouse_size='X-SMALL'
auto_suspend=180
auto_resume=true
initially_suspended=true;

CREATE OR REPLACE TRANSIENT TABLE SUPPLIER 
as
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.SUPPLIER;
use warehouse w1;
show warehouses;

SELECT * FROM SUPPLIER;

ALTER SESSION set USE_CACHED_RESULT = false;


CREATE OR REPLACE TABLE CUSTOMER_CLUSTERED
LIKE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER;

CREATE OR REPLACE TABLE CUSTOMER_NOCLUSTERED
LIKE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER;

SELECT * FROM CUSTOMER_CLUSTERED;

ALTER TABLE CUSTOMER_CLUSTERED CLUSTER BY (C_MKTSEGMENT);
INSERT INTO CUSTOMER_CLUSTERED
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER;


SELECT SYSTEM$CLUSTERING_INFORMATION('CUSTOMER_CLUSTERED');
SELECT SYSTEM$CLUSTERING_INFORMATION('CUSTOMER_NOCLUSTERED', '(C_MKTSEGMENT)');
SELECT C_MKTSEGMENT, count(*) 
FROM CUSTOMER_CLUSTERED 
GROUP BY C_MKTSEGMENT
LIMIT 100;

